/**
 * Font Manager - Anti-aliased Font Rendering
 * 
 * Uses pre-rendered Segoe UI font data from segoe_font_data.h
 * Generated by tools/generate_font.py
 */

#include "font_manager.h"
#include "segoe_font_data.h"
#include "../../../drivers/gfx.h"

/* Map pixel size to font_sizes index */
static int size_to_index(int size) {
    switch (size) {
        case 12: return 0;
        case 14: return 1;
        case 16: return 2;
        case 18: return 3;
        case 24: return 4;
        default: return 2;  /* Default to 16px */
    }
}

void font_init(void) {
    /* Nothing to initialize - all data is static */
}

int font_get_line_height(int size) {
    return font_sizes[size_to_index(size)].line_height + 2;  /* Add 2px line gap */
}

int font_draw_char(int x, int y, char c, uint32_t color, int size) {
    /* Get font for requested size */
    const FontSize* font = &font_sizes[size_to_index(size)];
    
    /* Check character range */
    if (c < FONT_CHAR_START || c > FONT_CHAR_END) {
        /* Return space width for invalid chars */
        return font->glyphs['I' - FONT_CHAR_START].advance;
    }
    
    /* Get glyph info */
    int glyph_idx = c - FONT_CHAR_START;
    const FontGlyph* glyph = &font->glyphs[glyph_idx];
    
    /* Handle space - just return advance, no drawing */
    if (c == ' ') {
        return glyph->advance;
    }
    
    /* Get pixel data pointer */
    const uint8_t* pixels = font->data + glyph->data_offset;
    
    /* Calculate draw position using bearings */
    int draw_x = x + glyph->left;
    int draw_y = y + glyph->top;
    
    /* Draw the glyph with alpha blending */
    int row, col;
    for (row = 0; row < glyph->height; row++) {
        for (col = 0; col < glyph->width; col++) {
            uint8_t alpha = pixels[row * glyph->width + col];
            if (alpha > 0) {
                gfx_put_pixel_alpha(draw_x + col, draw_y + row, color, alpha);
            }
        }
    }
    
    return glyph->advance;
}

int font_draw_string(int x, int y, const char* text, uint32_t color, int size) {
    int cursor = x;
    
    while (*text) {
        cursor += font_draw_char(cursor, y, *text, color, size);
        text++;
    }
    
    return cursor - x;
}

int font_get_char_width(char c, int size) {
    const FontSize* font = &font_sizes[size_to_index(size)];
    
    if (c < FONT_CHAR_START || c > FONT_CHAR_END) {
        return font->glyphs['I' - FONT_CHAR_START].advance;
    }
    
    return font->glyphs[c - FONT_CHAR_START].advance;
}

int font_get_string_width(const char* text, int size) {
    int width = 0;
    
    while (*text) {
        width += font_get_char_width(*text, size);
        text++;
    }
    
    return width;
}
