/**
 * Font Manager - Anti-aliased Font Rendering
 * 
 * Uses pre-rendered Segoe UI font data (generated by tools/generate_font.py)
 * Supports sizes: 12, 14, 16, 18, 24px
 */

#ifndef FONT_MANAGER_H
#define FONT_MANAGER_H

#include <stdint.h>

/* Available font sizes */
#define FONT_SIZE_12  12
#define FONT_SIZE_14  14
#define FONT_SIZE_16  16   /* Default */
#define FONT_SIZE_18  18
#define FONT_SIZE_24  24

/**
 * Initialize font manager
 */
void font_init(void);

/**
 * Get line height for a given font size
 * @param size Font size (12, 14, 16, 18, 24)
 */
int font_get_line_height(int size);

/**
 * Draw a single character with anti-aliasing
 * @param x X position
 * @param y Y position (top of character)
 * @param c Character to draw (ASCII 32-126)
 * @param color RGB color (0xRRGGBB)
 * @param size Font size (12, 14, 16, 18, 24)
 * @return Width of character drawn (for cursor advancement)
 */
int font_draw_char(int x, int y, char c, uint32_t color, int size);

/**
 * Draw a string with anti-aliasing
 * @param x X position
 * @param y Y position (top of text)
 * @param text String to draw
 * @param color RGB color (0xRRGGBB)
 * @return Total width of string drawn
 */
/**
 * Draw a string with anti-aliased font
 * @param x X position
 * @param y Y position (top of text)
 * @param text String to draw
 * @param color RGB color (0xRRGGBB)
 * @param size Font size (12, 14, 16, 18, 24)
 * @return Width of string drawn
 */
int font_draw_string(int x, int y, const char* text, uint32_t color, int size);

/**
 * Get width of a string without drawing
 * @param text String to measure
 * @param size Font size (12, 14, 16, 18, 24)
 * @return Width in pixels
 */
int font_get_string_width(const char* text, int size);

/**
 * Get width of a single character
 * @param c Character to measure
 * @param size Font size (12, 14, 16, 18, 24)
 * @return Width in pixels
 */
int font_get_char_width(char c, int size);

#endif /* FONT_MANAGER_H */
