#!/usr/bin/env python3
"""
MaahiOS Font Generator - Fixed Version
=======================================
Generates anti-aliased bitmap font data from Segoe UI.

Key fix: Render each character in its own properly-sized cell with 
correct positioning for consistent baseline alignment.
"""

from PIL import Image, ImageDraw, ImageFont
import os
import sys

# =============================================================================
# CONFIGURATION
# =============================================================================

FONT_SIZES = [12, 14, 16, 18, 24]

CHAR_START = 32   # Space
CHAR_END = 126    # Tilde ~
CHAR_COUNT = CHAR_END - CHAR_START + 1

FONT_PATHS = [
    "C:/Windows/Fonts/segoeui.ttf",
    "C:/Windows/Fonts/arial.ttf",
    "C:/Windows/Fonts/calibri.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
]

OUTPUT_FILE = "../src/system/libraries/libgui/fonts/segoe_font_data.h"

# =============================================================================
# FONT LOADING
# =============================================================================

def find_font():
    for path in FONT_PATHS:
        if os.path.exists(path):
            print(f"Using font: {path}")
            return path
    print("ERROR: No suitable font found!")
    sys.exit(1)

# =============================================================================
# GLYPH RENDERING - PROPER APPROACH
# =============================================================================

def render_font_size(font_path, size):
    """
    Render all glyphs with proper metrics.
    Each glyph gets its advance width for proper spacing.
    """
    font = ImageFont.truetype(font_path, size)
    
    # Get font metrics
    ascent, descent = font.getmetrics()
    line_height = ascent + descent
    
    glyphs = []
    
    for code in range(CHAR_START, CHAR_END + 1):
        char = chr(code)
        
        # Get the advance width (how far to move cursor after this char)
        try:
            advance = int(font.getlength(char))
        except:
            advance = size // 2
        
        if advance < 1:
            advance = size // 3  # Minimum for space-like chars
        
        # Get bounding box for actual ink
        bbox = font.getbbox(char)
        
        if bbox is None or code == 32:  # Space
            # Space - no pixels, just advance
            space_advance = size // 3
            glyphs.append({
                'code': code,
                'char': ' ',
                'width': 1,
                'height': 1,
                'advance': space_advance,
                'pixels': [0]
            })
            continue
        
        left, top, right, bottom = bbox
        
        # Glyph dimensions based on bounding box
        glyph_width = right - left
        glyph_height = bottom - top
        
        if glyph_width < 1:
            glyph_width = 1
        if glyph_height < 1:
            glyph_height = 1
        
        # Create image exactly the size of the glyph
        img = Image.new('L', (glyph_width, glyph_height), 0)
        draw = ImageDraw.Draw(img)
        
        # Draw at offset to compensate for bbox origin
        draw.text((-left, -top), char, font=font, fill=255)
        
        # Get pixels
        pixels = list(img.getdata())
        
        glyphs.append({
            'code': code,
            'char': char,
            'width': glyph_width,
            'height': glyph_height,
            'advance': advance,
            'left': left,   # Left bearing (where to start drawing)
            'top': top,     # Top offset from baseline
            'pixels': pixels
        })
    
    return {
        'size': size,
        'line_height': line_height,
        'ascent': ascent,
        'descent': descent,
        'glyphs': glyphs
    }

# =============================================================================
# C CODE GENERATION
# =============================================================================

def generate_c_header(font_data_list, font_name):
    lines = []
    lines.append("/**")
    lines.append(f" * {font_name} Font Data - Auto-generated")
    lines.append(" * Generated by tools/generate_font.py")
    lines.append(" * DO NOT EDIT MANUALLY")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef SEGOE_FONT_DATA_H")
    lines.append("#define SEGOE_FONT_DATA_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define FONT_CHAR_START {CHAR_START}")
    lines.append(f"#define FONT_CHAR_END   {CHAR_END}")
    lines.append(f"#define FONT_CHAR_COUNT {CHAR_COUNT}")
    lines.append("")
    
    lines.append("/* Glyph metadata */")
    lines.append("typedef struct {")
    lines.append("    uint8_t  width;       /* Glyph bitmap width */")
    lines.append("    uint8_t  height;      /* Glyph bitmap height */")
    lines.append("    int8_t   left;        /* Left bearing (x offset) */")
    lines.append("    int8_t   top;         /* Top offset from baseline */")
    lines.append("    uint8_t  advance;     /* Cursor advance */")
    lines.append("    uint16_t data_offset; /* Offset into pixel data */")
    lines.append("} FontGlyph;")
    lines.append("")
    
    for font_data in font_data_list:
        size = font_data['size']
        line_h = font_data['line_height']
        ascent = font_data['ascent']
        
        lines.append(f"/* ========== {size}px Font ========== */")
        lines.append(f"#define FONT_{size}PX_LINE_HEIGHT {line_h}")
        lines.append(f"#define FONT_{size}PX_ASCENT {ascent}")
        lines.append("")
        
        lines.append(f"static const uint8_t font_{size}px_data[] = {{")
        
        offset = 0
        glyph_info = []
        
        for g in font_data['glyphs']:
            left_val = g.get('left', 0)
            top_val = g.get('top', 0)
            
            glyph_info.append({
                'width': g['width'],
                'height': g['height'],
                'left': left_val,
                'top': top_val,
                'advance': g['advance'],
                'offset': offset
            })
            
            if g['pixels']:
                char_display = g['char'] if g['code'] >= 33 and g['code'] != 92 else f"0x{g['code']:02X}"
                lines.append(f"    /* '{char_display}' {g['width']}x{g['height']} adv={g['advance']} */")
                
                chunk_size = 16
                for i in range(0, len(g['pixels']), chunk_size):
                    chunk = g['pixels'][i:i + chunk_size]
                    chunk_str = ','.join(f"{p:3d}" for p in chunk)
                    lines.append(f"    {chunk_str},")
                
                offset += len(g['pixels'])
        
        lines.append("};")
        lines.append("")
        
        lines.append(f"static const FontGlyph font_{size}px_glyphs[FONT_CHAR_COUNT] = {{")
        
        for i, info in enumerate(glyph_info):
            code = CHAR_START + i
            char = chr(code) if code >= 33 and code != 92 else f"0x{code:02X}"
            left_s = info['left'] if info['left'] >= 0 else info['left']
            top_s = info['top'] if info['top'] >= 0 else info['top']
            lines.append(f"    {{ {info['width']:2d}, {info['height']:2d}, {left_s:3d}, {top_s:3d}, {info['advance']:2d}, {info['offset']:5d} }}, /* '{char}' */")
        
        lines.append("};")
        lines.append("")
    
    lines.append(f"#define FONT_SIZE_COUNT {len(font_data_list)}")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    uint8_t size;")
    lines.append("    uint8_t line_height;")
    lines.append("    uint8_t ascent;")
    lines.append("    const FontGlyph* glyphs;")
    lines.append("    const uint8_t* data;")
    lines.append("} FontSize;")
    lines.append("")
    lines.append("static const FontSize font_sizes[FONT_SIZE_COUNT] = {")
    
    for font_data in font_data_list:
        size = font_data['size']
        line_h = font_data['line_height']
        ascent = font_data['ascent']
        lines.append(f"    {{ {size}, {line_h}, {ascent}, font_{size}px_glyphs, font_{size}px_data }},")
    
    lines.append("};")
    lines.append("")
    lines.append("#endif /* SEGOE_FONT_DATA_H */")
    
    return '\n'.join(lines)

# =============================================================================
# MAIN
# =============================================================================

def main():
    print("=" * 60)
    print("MaahiOS Font Generator")
    print("=" * 60)
    
    font_path = find_font()
    font_name = os.path.basename(font_path).replace('.ttf', '')
    
    font_data_list = []
    total_bytes = 0
    
    for size in FONT_SIZES:
        print(f"Generating {size}px...")
        data = render_font_size(font_path, size)
        font_data_list.append(data)
        
        bytes_for_size = sum(len(g['pixels']) for g in data['glyphs'])
        total_bytes += bytes_for_size
        print(f"  - line_height={data['line_height']}, ascent={data['ascent']}, {bytes_for_size:,} bytes")
    
    print(f"\nTotal: {total_bytes:,} bytes ({total_bytes/1024:.1f} KB)")
    
    header_content = generate_c_header(font_data_list, font_name)
    
    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.normpath(os.path.join(script_dir, OUTPUT_FILE))
    
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with open(output_path, 'w') as f:
        f.write(header_content)
    
    print(f"Written to: {output_path}")
    print("DONE!")

if __name__ == "__main__":
    main()
